name: First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Helo from Github Actions"

            - name: List Files
              run: ls

            - name: Cat Readme
              run: cat README.md

              