name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout REPO
              uses: actions/checkout@v4

            - name: List Repo files
              run: ls -latr

            - name: Executing shell script
              run: |
                chmod +x ./ascii-script.sh
                ./ascii-script.sh

            - name: Upload Dragon
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt

    ascii_job2:
        needs: ascii_job     
        runs-on: ubuntu-latest
        steps:
            - name: Checkout REPO
              uses: actions/checkout@v4

            - name: List Repo files
              run: ls -latr

            - name: Download Dragon
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file                

            - name: List Repo files after download dragon
              run: ls -latr

            # - name: Install conwsay
            #   run: sudo apt-get install cowsay -y

            # - name: Generate ASCII Artwork
            #   run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

            # - name: Test file exists
            #   run: grep -i "dragon" dragon.txt

            # - name: Cat file
            #   run: cat dragon.txt

            # - name: List Repo files
            #   run: ls -latr