name: Variables and Secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io
    #DOCKER_USERNAME: fsainovich
    IMAGE_NAME: flask-env-var

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout REPO
              uses: actions/checkout@v4

            - name: Docker build
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker login
              #env:
              #  DOCKER_PASSWORD: thepassord
              run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Push 
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker        
        runs-on: ubuntu-latest
        steps:
            - name: Checkout REPO
              uses: actions/checkout@v4

            - name: Docker run
              run: echo docker run $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
